<?php

declare(strict_types=1);

namespace App\Migration\Example;

// Domain Layer
use App\Shared\Core\Enums\RecordStatus;
// Infrastructure Layer

// PSR Interfaces
use Psr\Clock\ClockInterface;
// Vendor Layer
use Yiisoft\Db\Migration\MigrationBuilder;
use Yiisoft\Db\Migration\RevertibleMigrationInterface;

/**
 * Creates another_example table with status tracking and JSON detail_info.
 */
final class M20260910104729CreateAnotherExampleTable implements RevertibleMigrationInterface
{
    private const TABLE_NAME = 'another_example';

    public function __construct(
        private ClockInterface $clock
    ) {
    }

    public function up(MigrationBuilder $b): void
    {
        $cb = $b->columnBuilder();

        $b->createTable(self::TABLE_NAME, [
            'id'          => $cb::integer()->notNull()->extra('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'name'        => $cb::string(255)->notNull(),
            'example_id'  => $cb::integer()->notNull(),
            'status'      => $cb::smallint()->notNull()->defaultValue(RecordStatus::DRAFT->value),
            'detail_info' => $cb::json()->notNull()->defaultValue([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ]),
            'origin_id'    => $cb::integer()->null()->comment('origin instance id where the record comes from or goes to'),
            'sync_flag'    => $cb::smallint()->null()->defaultValue(1)->comment('null: synced, 1: not synced'),
            'sync_mdb'     => $cb::smallint()->null()->comment('null: sync to MDB, 1: not sync to MDB'),
            'lock_version' => $cb::integer()->notNull()->defaultValue(1)->comment('Optimistic locking version'),
        ]);
    }

    public function down(MigrationBuilder $b): void
    {
        $b->dropTable(self::TABLE_NAME);
    }
}
